object Versions {
    const val gradlePlugin = "7.4.2"
    const val kotlin = "1.8.21"
    const val googleServices = "4.3.15"

    const val koin = "3.4.0"
    const val coroutines = "1.7.1"
    const val lifecycle = "2.6.1"
    const val system_ui_controller = "0.20.3"
    const val navigationKtx = "2.6.0"
    const val accompanistPermissions = "0.27.1"
    const val composeUi = "1.4.3"
    const val composeMaterial3 = "1.1.0"
    const val composeNavigation = "2.6.0"
    const val composeActivity = "1.7.2"
    const val composeKoin = "3.4.5"
    const val firebaseBom = "32.1.1"
    const val googleAds = "22.2.0"
    const val retrofit = "2.9.0"
    const val retrofitCoroutines = "0.9.2"
    const val retrofitConverter = "2.9.0"
    const val okhttpInterceptor = "4.10.0"

    const val junit5 = "5.8.2"
    const val mockk = "1.13.2"

    const val mockkAndroid = "1.12.0"
    const val junitAndroid = "1.1.5"
    const val espressoAndroid = "3.5.1"
    const val androidTestRunner = "1.5.2"
    const val androidTestRules = "1.5.0"
    const val uiAutomator = "2.2.0"
}