name: Build Release signed app

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Write run number to properties
        run: echo ciBuildNumber=${{ github.run_number }} > ./local.properties

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}
          echo "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}

      - name: Build Release signed apk
        run: ./gradlew app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename built artifact
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.apk

      - name: Move artifacts to proper dir
        run: |
          mkdir app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          mv app/build/outputs/* app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          mv app/build/generated/source/* app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          mv app/build/intermediates/merged_manifests/* app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

      - name: Create archive
        run: tar -czvf app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.tar.gz app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          path: app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

      - name: Upload release apk
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.apk
          path: app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}/apk/release/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.apk
